[package]
name = "toha"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"

[features]
default = ["cli"]
cli = ["dep:clap", "dep:inquire", "dep:include_dir"]

[dependencies]
minijinja = { version = "2.24", default-features = false, features = ["builtins", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_norway = "0.9"
indexmap = { version = "2", features = ["serde"] }
thiserror = "2"
clap = { version = "4", features = ["derive"], optional = true }
jiff = "0.2.37"
heck = "0.5.0"
regex = "1.13.1"
toml = "1.1.6"
jsonschema = { version = "0.58.0", default-features = false }
globset = "0.4"
sha2 = "0.10"
inquire = { version = "0.9.4", features = ["editor"], optional = true }
tempfile = "3"
gix = { version = "0.87.1", default-features = false, features = ["blocking-network-client", "blocking-http-transport-curl-rustls", "worktree-mutation", "revision", "sha1"] }
include_dir = { version = "0.7.4", optional = true }

[build-dependencies]
tagver = "0.1.4"

[dev-dependencies]
assert_cmd = "2"
pretty_assertions = "1"
expectrl = "0.9.0"
rustls = "0.23"

[[bin]]
name = "toha"
path = "src/main.rs"
required-features = ["cli"]
